### ISSUE TITLE
Want to implement it in an real app, can someone guide for the backend function

### ISSUE THREAD

**Issue by varunbhalerao56** [MarcinusX/flutter_stripe_demo#1]
Hi saw your video about this project, and i want to implement it in flutter (production) do you have an example of the backend function cause i am not familiar that much with Js.

Please that would be a great help thank you.

**Comment by MarcinusX** [comment]
You can find the official tutorial with backend snippet in here https://stripe.com/docs/payments/accept-a-payment?integration=checkout#create-a-checkout-session.

Although if you don't feel comfortable with backend development, it may be wise to delegate it to the backend developer to avoid potential sensitive data leaks.
