### ISSUE TITLE
How to replace nikesPriceId

### ISSUE THREAD

**Issue by zakblacki** [MarcinusX/flutter_stripe_demo#8]
I'm getting this error because of nikesPriceId, where do I find it in stripe to replace  ? 

>  {"error":{"code":"resource_missing","doc_url":"https://stripe.com/docs/error-codes/resource-missing","message":"No such price: 'price_1HFw3QAQHy2zYPZft7bbrtWZ'","param":"line_items[0][price]","type":"invalid_request_error"}}
> E/flutter ( 9306): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: DioError [DioErrorType.RESPONSE]: Http status error [400]

**Comment by MarcinusX** [comment]
it's the price id of product you want to sell :)
You get it from Stripe Dashboard.
